// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/md": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "md"
                ],
                "summary": "Retrieve All Markdown Snippets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.MarkdownSnippetListItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "md"
                ],
                "summary": "Create new a markdown snippet",
                "parameters": [
                    {
                        "description": "Post Body",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateMarkdownSnippet"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.MarkdownSnippet"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "md"
                ],
                "summary": "Updates a markdown snippet",
                "parameters": [
                    {
                        "description": "Patch Body",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateMarkdownSnippet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MarkdownSnippet"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    }
                }
            }
        },
        "/md/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "md"
                ],
                "summary": "Retrieve Markdown Snippet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Snippet uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MarkdownSnippet"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "md"
                ],
                "summary": "Removes MarkdownSnippet permanantly",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Snippet uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ApiResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "format": "int",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "format": "string"
                }
            }
        },
        "model.CreateMarkdownSnippet": {
            "type": "object",
            "required": [
                "body"
            ],
            "properties": {
                "body": {
                    "description": "Markdown body to save.",
                    "type": "string",
                    "maxLength": 1024,
                    "minLength": 1
                }
            }
        },
        "model.MarkdownSnippet": {
            "type": "object",
            "required": [
                "body"
            ],
            "properties": {
                "body": {
                    "description": "Markdown body to save.",
                    "type": "string",
                    "minLength": 1
                },
                "createDate": {
                    "description": "Date markdown snippet was created",
                    "type": "string",
                    "format": "date-time",
                    "readOnly": true
                },
                "id": {
                    "description": "Markdown snippet guid.",
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "model.MarkdownSnippetListItem": {
            "type": "object",
            "properties": {
                "createDate": {
                    "description": "Date markdown snippet was created",
                    "type": "string",
                    "format": "date-time",
                    "readOnly": true
                },
                "id": {
                    "description": "Markdown snippet guid.",
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "model.UpdateMarkdownSnippet": {
            "type": "object",
            "required": [
                "body"
            ],
            "properties": {
                "body": {
                    "description": "Markdown body to save.",
                    "type": "string",
                    "minLength": 1
                },
                "id": {
                    "description": "Markdown snippet guid.",
                    "type": "string",
                    "format": "uuid"
                }
            }
        }
    },
    "tags": [
        {
            "name": "md"
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:3000",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "SouLxSnippets",
	Description: "Backend API for storing and retrieving markdown snippets",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
