definitions:
  api.ErrorResponse:
    properties:
      code:
        example: 400
        format: int
        type: integer
      message:
        format: string
        type: string
    type: object
  md.CreateMDReq:
    properties:
      body:
        description: Markdown body to save.
        example: |-
          # Markdown Snippet
          Some Text
        maxLength: 64000
        minLength: 1
        type: string
      title:
        description: Markdown snippet title.
        example: SouLxBurN Is Awesome!
        maxLength: 64
        minLength: 1
        type: string
    required:
    - body
    - title
    type: object
  md.MDListItem:
    properties:
      createDate:
        description: Date markdown snippet was created
        format: date-time
        type: string
      id:
        description: Markdown snippet guid.
        format: uuid
        type: string
      title:
        description: Markdown snippet title.
        example: SouLxBurN Is Awesome!
        type: string
    type: object
  md.MarkdownSnippet:
    properties:
      body:
        description: Markdown body to save.
        example: |-
          # Markdown Snippet
          Some Text
        type: string
      createDate:
        description: Date markdown snippet was created.
        format: date-time
        type: string
      id:
        description: Markdown snippet guid.
        format: uuid
        type: string
      title:
        description: Markdown snippet title.
        example: SouLxBurN Is Awesome!
        type: string
      updateKey:
        description: Update hash key allowing the snippet to be updated.
        format: uuid
        type: string
    type: object
  md.UpdateMDReq:
    properties:
      body:
        description: Markdown body to save.
        example: |-
          # Markdown Snippet
          Some Text
        maxLength: 64000
        minLength: 1
        type: string
      id:
        description: Markdown snippet guid.
        format: uuid
        type: string
      title:
        description: Markdown snippet title.
        example: SouLxBurN Is Awesome!
        maxLength: 64
        minLength: 1
        type: string
      updateKey:
        description: UpdateKey required for updating snippet.
        format: uuid
        type: string
    required:
    - body
    - id
    - title
    - updateKey
    type: object
info:
  contact: {}
  description: API for storing and retrieving markdown snippets.\nBuilt live on stream
    @twitch.tv/soulxburn
  title: MDSnips
  version: "1.0"
paths:
  /md:
    get:
      consumes:
      - application/json
      deprecated: true
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/md.MDListItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Retrieve All Markdown Snippets
      tags:
      - md
    patch:
      consumes:
      - application/json
      parameters:
      - description: Patch Body
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/md.UpdateMDReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/md.MarkdownSnippet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Updates a markdown snippet
      tags:
      - md
    post:
      consumes:
      - application/json
      parameters:
      - description: Post Body
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/md.CreateMDReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/md.MarkdownSnippet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Create new a markdown snippet
      tags:
      - md
  /md/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Snippet uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Removes MarkdownSnippet permanantly
      tags:
      - md
    get:
      consumes:
      - application/json
      parameters:
      - description: Snippet uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/md.MarkdownSnippet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Retrieve Markdown Snippet
      tags:
      - md
  /md/search:
    get:
      consumes:
      - application/json
      parameters:
      - description: Search Term
        in: query
        name: text
        type: string
      - default: 10
        description: Number of Snippets
        in: query
        name: limit
        type: integer
      - default: 0
        description: Skip Number of Snippets
        in: query
        name: skip
        type: integer
      - description: Sort By
        enum:
        - createDate_ASC
        - createDate_DESC
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/md.MDListItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Search, Sort, and paginate through MarkdownSnippets.
      tags:
      - md
swagger: "2.0"
tags:
- name: md
